name = "HTTP2"
uuid = "0ee529b6-85a9-4020-94aa-d5b2735f286b"
license = "MIT"
desc = "Implementation of HTTP/2"
authors = ["Tanmay Mohapatra <tanmaykm@gmail.com>", "ScottPJones <scottjones@alum.mit.edu>"]
version = "0.3.0"

[deps]
HPack = "28024e5f-9f70-4280-80a2-4be20479eed3"
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"

[compat]
MbedTLS = "1.0"
julia = "1.5"

[extras]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Sockets", "Dates"]
